# Generated by Django 5.0.2 on 2024-02-26 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date of payment')),
                ('amount', models.PositiveIntegerField(verbose_name='Amount')),
                ('method', models.CharField(choices=[('C', 'Cash'), ('T', 'Translation')], max_length=1)),
                ('url_for_payment', models.CharField(blank=True, max_length=500, null=True, verbose_name='url for payment')),
                ('status', models.CharField(blank=True, choices=[('P', 'Process'), ('S', 'SUCCESS'), ('C', 'CANCELED')], max_length=1, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.course', verbose_name='Course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.lesson', verbose_name='Lesson')),
            ],
        ),
    ]
