# Generated by Django 5.0.2 on 2024-02-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название курса')),
                ('course_image', models.ImageField(blank=True, null=True, upload_to='course', verbose_name='изображение')),
                ('description', models.TextField(verbose_name='описание курса')),
                ('price', models.PositiveIntegerField(default=1000, verbose_name='стоимость курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название урока')),
                ('lesson_image', models.ImageField(blank=True, null=True, upload_to='course', verbose_name='изображение')),
                ('description', models.TextField(verbose_name='описание урока')),
                ('link', models.CharField(max_length=200, verbose_name='ссылка')),
                ('price', models.PositiveIntegerField(default=100, verbose_name='стоимость урока')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
